name: Keep Repository Active

on:
  schedule:
    # 매주 월요일 실행 (60일 비활성화 방지)
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Keep alive
      run: |
        echo "Keep repository active - $(date)" >> keep-alive.log
        
    - name: Commit if needed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add keep-alive.log || true
        git commit -m "Keep repository active [skip ci]" || echo "No changes"
        git push || echo "No push needed"