name: Send to WhatsApp

on:
  # schedule:
  #   # 매일 오전 8시 전송 (한국시간)
  #   - cron: '0 23 * * *'  # UTC 기준 (KST 08:00)
  workflow_dispatch:  # 수동 실행만 가능
  
permissions:
  contents: write

jobs:
  send:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Send to WhatsApp
      env:
        GREEN_API_INSTANCE_ID: ${{ secrets.GREEN_API_INSTANCE_ID }}
        GREEN_API_TOKEN: ${{ secrets.GREEN_API_TOKEN }}
      run: |
        echo "=== WhatsApp 전송 시작 ==="
        echo "Green API Instance ID 길이: ${#GREEN_API_INSTANCE_ID}"
        echo "Green API Token 길이: ${#GREEN_API_TOKEN}"
        
        # Green API 사용 (Whapi 서비스 중단으로 변경)
        python -u scripts/send_whatsapp_green.py
    
    - name: Update send history
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f data/history/*.json || echo "No history files to add"
        git commit -m "Update send history [$(date '+%Y-%m-%d %H:%M:%S')]" || echo "No changes to commit"
        git push